[phases.build]
cmds = ["mvn clean package -DskipTests"]

[phases.start]
cmd = "java -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC -Dserver.port=${PORT:-8080} -jar target/washgo-0.0.1-SNAPSHOT.jar"

[variables]
MAVEN_OPTS = "-Xmx1024m"